before:
  hooks:
    - go mod download

builds:
  - main: .
    id: PAL9000
    binary: PAL9000
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
dockers:
  - id: PAL9000
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/pandodao/{{ .ProjectName }}:latest"
      - "ghcr.io/pandodao/{{ .ProjectName }}:{{ .Major }}"
      - "ghcr.io/pandodao/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/pandodao/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
blobs:
  - provider: s3
    region: us-east-2
    bucket: goreleaser-builds
    folder: "PAL9000"
