name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: ${{ github.repository_owner != github.actor }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: "Docker login"
        run: docker login ghcr.io -u docker -p ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.BE_DEPLOYER_AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BE_DEPLOYER_AWS_SECRET }}
